[package]
name = "bounce-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
prost = "0.13.3"
toml = "0.8.19"

[build-dependencies]
prost-build = "0.13.3"
tonic-build = "0.12.3"

[[bin]]
name = "ss"
path = "src/ss.rs"

[[bin]]
name = "gs"
path = "src/gs.rs"

[[bin]]
name = "sat"
path = "src/sat.rs"

[[bin]]
name = "mc"
path = "src/mc.rs"
