[mc]
ip = "127.0.0.1"
num_keys = 2
num_ss = 1
num_gs = 1
num_sat = 1
f = 0

[[ss]]
ip = "127.0.0.1"

[[gs]]
ip = "127.0.0.1"

#[[sat]]
#ip = "127.0.0.1"

#[[sat]]
#ip = "71.172.153.155"

#[[sat]]
#ip = "192.168.1.167"

#[[sat]]
#ip = "192.168.1.20"

[[sat]]
ip = "47.129.171.144"


[fanout]
fanout = 3
