#[mc]
#ip = "198.22.255.20"
#
#[[ss]]
#ip = "128.110.219.17"
#
#[[gs]]
#ip = "128.105.145.26"
#
#[[sat]]
#ip = "127.0.0.1"

[mc]
ip = "127.0.0.1"
num_keys = 2
num_ss = 1
num_gs = 1
num_sat = 1

[[ss]]
ip = "127.0.0.1"

[[gs]]
ip = "127.0.0.1"

[[sat]]
ip = "127.0.0.1"